spring.application.name=recommendation

application.recommendations-db.url=jdbc:h2:file:./transaction;ACCESS_MODE_DATA=r
spring.datasource.driver-class-name=org.h2.Driver

recommendation.datasource.url=jdbc:postgresql://localhost:5432/recommendation_db
recommendation.datasource.username=
recommendation.datasource.password=
recommendation.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:/db/changelog-master.yaml