spring.application.name=recommendation

application.recommendations-db.url=jdbc:h2:file:./transaction;ACCESS_MODE_DATA=r

recommendation.datasource.url=jdbc:postgresql://localhost:5432/recommendation_db
recommendation.datasource.username=postgres
recommendation.datasource.password=postgres
spring.datasource.driver-class-name=org.h2.Driver

spring.liquibase.change-log=classpath:/db/changelog-master.yaml

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.enabled=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

telegram.bot.token=8866652043:AAG5swrGvEmJ7RAB2EkBkrHj6vyjHbQCzhg